name: validate-mdx-links
on:
  pull_request:
    paths:
      # we run to check if the links are wrong
      - 'packages/web/docs/src/**/*.mdx'
      # or if a page disappeared
      - 'packages/web/docs/src/app/**'

jobs:
  validate-mdx-links:
    runs-on: ubuntu-22.04
    timeout-minutes: 4
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: setup environment
        uses: ./.github/actions/setup
        with:
          actor: validate-mdx-links
          cacheTurbo: false

      - name: validate links in docs
        run: bash -c './scripts/validate-mdx-links.ts --cwd packages/web/docs'
